# A: Lexical Grammar for POSIX Shell



## A.0: Ignorable

newline			::= ? newline character on system ?

tabulator		::= ? tab character on system ?

null-join		::= ? matching nothing to join ?

whitespace		::= ' ' | tabulator

skip-newline		::= '\' newline

no-newline		::= ? anything but newline ?

comment			::= '#' { no-newline } newline

ignorable		::= whitespace | comment | skip-newline



## A.1: Basics

natural-digit		::= '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'

digit			::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'

upper-case 		::= 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J'
	 	          | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T'
	 	          | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z'

lower-case 		::= 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j'
	        	  | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't'
		          | 'u' | 'v' | 'w' | 'x' | 'y' | 'z'

punctuation 		::= '.' | ',' | ';' | ':' | '!' | '?' | '-' | '_' | '(' | ')' 
	 	          | '{' | '}' | '[' | ']' | '"' | "'" | '`' | '@' | '#' 
		          | '$' | '%' | '^' | '&' | '*' | '+' | '=' | '<' | '>' 
		          | '/' | '|' | '~' | '\'



alphabetic		::= upper-case | lower-case

alphanumeric		::= alphabetic | digit

printable		::= punctuation | alphanumeric

escape-character	::= '\' ( '$' | '`' | '"' | '\' | newline )

## A.2: Integer & Identifier

identifier-prefix	::= alphabetic | '_'

identifier-suffix	::= alphanumeric | '_'

identifier		::= identifier-prefix { identifier-suffix }

integer			::= { digit }


# B: Syntactc Grammar for POSIX Shell

## B.1: Quoting

single-quote		::= "'" { printable } "'"

double-quote		::= '"' { parameter-expansion 
				| command-substitution 
				| escape-character
				| printable } '"'

quoted-literal		::= single-quote | double-quote


## B.2: Positional Parameters


positional-number	::= { natural-digit }


positional-parameter	::= '$' null-join positional-number


## B.3: Special Parameters


special-param-all-pos-a ::= '@'

special-param-all-pos-b ::= '*'

special-param-pos-num   ::= '#'

special-param-last-exit ::= '?'

special-param-async-job ::= '!'

special-param-proc-id 	::= '$'

special-param-flag-opts ::= '-'

special-param-env-name  ::= '0'

special-param-ifs	::= "IFS"

special-params		::= '$' (
				    special-param-all-pos-a
				  | special-param-all-pos-b
				  | special-param-pos-num
				  | special-param-last-exit
				  | special-param-asyncp-job
				  | special-param-proc-id
				  | special-param-flag-opts
				  | special-param-env-name
				  | special-param-ifs
				)








